[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.ruff]
# Ruff is a super-fast linter that replaces Flake8 & isort
line-length = 88
target-version = "py311"
select = ["E", "F", "I"] # E=Errors, F=Pyflakes, I=Imports sorting
ignore = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]